version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: meal-planner-db
    environment:
      POSTGRES_DB: meal_planner
      POSTGRES_USER: meal_user
      POSTGRES_PASSWORD: meal_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meal-planner-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meal-planner-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - meal-planner-network
    volumes:
      - ./backend/logs:/app/logs

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meal-planner-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
      REACT_APP_OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - meal-planner-network
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  postgres_data:

networks:
  meal-planner-network:
    driver: bridge 