services:
  - type: web
    name: fitfuel-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fitfuel-db
          property: connectionString

databases:
  - name: fitfuel-db
    databaseName: fitfuel_db
    user: fitfuel_user
    plan: free
