services:
  - type: web
    name: fitfuel-backend
    env: java
    plan: free
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -jar target/*.jar
    healthCheckPath: /api/meal-plan/recipes
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fitfuel-db
          property: connectionString

databases:
  - name: fitfuel-db
    databaseName: fitfuel_db
    user: fitfuel_user
    plan: free
